# Generated by Django 2.1.3 on 2018-11-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.TextField(),
        ),
    ]
