# Generated by Django 2.1.3 on 2018-12-01 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20181128_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='categoryname',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='name',
            new_name='placename',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='name',
            new_name='publishername',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='name',
            new_name='titlename',
        ),
    ]
